name: Automatically deploy the project

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy'
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - uses: actions/checkout@v2
      name: Checkout code
    - name: Run paper-nms init
      if: steps.cache-paperclip-jars.outputs.cache-hit != 'true'
      run: |
        mvn paper-nms:init -pl nms/1_21
    - name: Setup GPG keys
      run: cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
    - name: Automatically deploy the project
      env:
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        deploy_password: ${{ secrets.DEPLOY_PASSWORD }}
      run: bash ./.github/deployment/deploy.sh "$gpg_passphrase" "$deploy_password"
