name: Publish package to GitHub Packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - name: Cache Paper(clip) jars
        id: cache-paperclip-jars
        uses: actions/cache@v2
        with:
          path: |
            .paper-nms
            build
            paperclip
            ~/.m2/repository/io/papermc/paper
            ~/.m2/repository/ca/bkaw/paper-nms
          key: ${{ runner.os }}-${{ secrets.CACHE_VERSION }}-paperclip
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - uses: actions/checkout@v2
        name: Checkout code
      - name: Run paper-nms init
        if: steps.cache-paperclip-jars.outputs.cache-hit != 'true'
        run: |
          mvn paper-nms:init -pl nms/1_21
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_PAT }}
